{
 "title": "Market Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "코스피", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "KOSPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kospi_kospi_index{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 코스피 지수"
    },
    {
     "expr": "kospi_kospi_index:ma5m{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 지수 평균"
    }
   ]
  },
  {
   "title": "변동성",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "stddev_over_time(kospi_kospi_index{job=\"market_exporter\", instance=\"devops_app:8000\"}[30m])",
     "legendFormat": "{{label_name}} 변동률"
    }
   ]
  },
  {
   "title": "코스피 지수",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyKRW" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kospi_kospi_index{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "환율", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "USD/KRW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyKRW" } },
   "targets": [
    {
     "expr": "market_USD_KRW{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 달러 환율"
    },
    {
     "expr": "market_USD_KRW:ma5m{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 달러 환율 평균"
    }
   ]
  },
  {
   "title": "JPY/KRW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyKRW" } },
   "targets": [
    {
     "expr": "market_JPY_KRW{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 엔화 환율"
    },
    {
     "expr": "market_JPY_KRW:ma5m{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 엔화 환율 평균"
    }
   ]
  },
  {
   "title": "달러 변동률",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "idelta(market_USD_KRW{job=\"market_exporter\", instance=\"devops_app:8000\"}[5m])",
     "legendFormat": "{{label_name}} 달러"
    }
   ]
  },
  {
   "title": "달러 환율",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyKRW" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "market_USD_KRW{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "엔화 변동률",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "idelta(market_JPY_KRW{job=\"market_exporter\", instance=\"devops_app:8000\"}[5m])",
     "legendFormat": "{{label_name}} 엔화"
    }
   ]
  },
  {
   "title": "엔 환율",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyKRW" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "market_JPY_KRW{instance=\"devops_app:8000\", job=\"market_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "해외 지수", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "다우존스",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyKRW" } },
   "targets": [
    {
     "expr": "dji_dji_index{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 다우존스 지수"
    },
    {
     "expr": "dji_dji_index:ma5m{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 지수 평균"
    }
   ]
  },
  {
   "title": "나스닥",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyKRW" } },
   "targets": [
    {
     "expr": "ixic_ixic_index{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 나스닥 지수"
    },
    {
     "expr": "ixic_ixic_index:ma5m{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 지수 평균"
    }
   ]
  },
  {
   "title": "S&P 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyKRW" } },
   "targets": [
    {
     "expr": "sp_sp_index{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} S&P 500"
    },
    {
     "expr": "sp_sp_index:ma5m{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 지수 평균"
    }
   ]
  },
  {
   "title": "니케이 225",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyKRW" } },
   "targets": [
    {
     "expr": "n225_n225_index{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 니케이 225 지수"
    },
    {
     "expr": "n225_n225_index:ma5m{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 지수 평균"
    }
   ]
  },
  {
   "title": "지수 별 변동률",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idelta(dji_dji_index{job=\"market_exporter\", instance=\"devops_app:8000\"}[5m])",
     "legendFormat": "{{label_name}} 다우존스"
    },
    {
     "expr": "idelta(ixic_ixic_index{job=\"market_exporter\", instance=\"devops_app:8000\"}[5m])",
     "legendFormat": "{{label_name}} 나스닥"
    },
    {
     "expr": "idelta(sp_sp_index{job=\"market_exporter\", instance=\"devops_app:8000\"}[5m])",
     "legendFormat": "{{label_name}} S&P 500"
    },
    {
     "expr": "idelta(n225_n225_index{job=\"market_exporter\", instance=\"devops_app:8000\"}[5m])",
     "legendFormat": "{{label_name}} 니케이 225"
    }
   ]
  },
  { "title": "금 및 유가", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "금 시세",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "currencyKRW" } },
   "targets": [
    {
     "expr": "gold_gold_price{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 국내 금 시세"
    },
    {
     "expr": "gold_gold_price:ma5m{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 금 시세 평균"
    }
   ]
  },
  {
   "title": "서부 텍사스유",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "wti_wti_index{instance=\"devops_app:8000\", job=\"market_exporter\"}",
     "legendFormat": "{{label_name}} 서부 텍사스유"
    },
    {
     "expr": "wti_wti_index:ma5m{instance=\"devops_app:8000\", job=\"market_exporter\"}",
     "legendFormat": "{{label_name}} WTI 시세 평균"
    }
   ]
  },
  {
   "title": "휘발유 시세",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "gasoline_gasoline_index{job=\"market_exporter\", instance=\"devops_app:8000\"}",
     "legendFormat": "{{label_name}} 휘발유 시세"
    },
    {
     "expr": "gasoline_gasoline_index:ma5m{instance=\"devops_app:8000\", job=\"market_exporter\"}",
     "legendFormat": "{{label_name}} 휘발유 시세 평균"
    }
   ]
  }
 ]
}